on:
  release:
    types: [created, edited, published]
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry run only
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  # Required for trusted publishing with OIDC
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: npm ci

      - name: Publish package
        if: >
          (github.event_name == 'release' && github.event.action == 'published') ||
          (github.event_name == 'workflow_dispatch' && !inputs.dryRun)
        run: npm publish --provenance --access public

      - name: Publish package (dry run)
        if: >
          (github.event_name == 'release' && github.event.action != 'published') ||
          (github.event_name == 'workflow_dispatch' && inputs.dryRun)
        run: npm publish --dry-run
